### ISSUE TITLE
resolveUri failed using cached image as preset

### ISSUE THREAD

**Issue by DavidWiesner** [tinyeeliu/androidquery#10]
I have a problem while using cached Images as preset.

``` java
Bitmap cached = aq.getCachedImage(url, 0);
if(cached != null){
    aq.id(view).image(url, true, true, 0, R.drawable.no_image, cached, 0);
}
```

The error message 
"resolveUri failed on bad bitmap uri: http://farm5.staticflickr.com/.....jpg"
is printed by the ImageView. I dont know why but the ImageView want to load the Drawable by his Uri by calling "resolveUri". But the Uri is set tu the Url of the original image and not to the filesystem.

**Comment by tinyeeliu** [comment]
Can you post the full url?

http://farm5.staticflickr.com/.....jpg

That's all I see in the link.
