### ISSUE TITLE
SSL Issues (Cloudflare Free SSL)

### ISSUE THREAD

**Issue by The-Don-Himself** [tinyeeliu/androidquery#115]
All my images show up blank. After much investigating, I realised the issue is the free cloudflare ssl. Since I am only using aQuery to load images, I do not mind completely disabling SSL validation checks but methods to do this vary greatly from tutorial to tutorial and from every stackoverflow question to another. It seems SocketFactory is depreciated, I found this link http://stackoverflow.com/questions/1217141/self-signed-ssl-acceptance-android but no solution is working. How can we disable this check easily in the latest version of aQuery? Thanks.

**Comment by PankovSerge** [comment]
What error you have got? I have the same problem, and get all time SSLHandshakeException

**Comment by The-Don-Himself** [comment]
I struggled with this for 2 days until I just gave up on aQuery all together. Sorry I cannot be of assistance.
