### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by darkovski88** [tinyeeliu/androidquery#118]
Hello,
I've just learned about this library but I'm not fully sure on how can i use it and how can i test is it working?

I've added these lines to my starting activity:

 MarketService ms = new MarketService(getActivity());
 ms.level(MarketService.MINOR).checkVersion();

Is this all i need?

Also is there a way to test this since I will upload my first version on playstore and a new after that but how can I be sure will it work?

**Comment by nologinatgit** [comment]
I think that this part of the library is deprecated as Google has changed its API.
