### ISSUE TITLE
D/ViewRootImpl@95cec59[Home]: ViewPostImeInputStage processPointer 0 & 1

### ISSUE THREAD

**Issue by heatkai** [tinyeeliu/androidquery#130]
Hello! A newbie here, I have a question about this. It's not really an error, but I can't make my firebase post working because of it.

It's coded in a fragment and it works just fine before but not anymore.
The expected output should be a toast message and firebase updated with new data.
My button is not working too, can someone help me and clarify what is my problem?

**METHOD**

`  private void userDetails() {

        databaseReference = FirebaseDatabase.getInstance().getReference("User Reports");
        String userDetails_ID = databaseReference.push().getKey();
        String userDetails_vehicleType = spin_vehicleType.getSelectedItem().toString().trim();
        String userDetails_name = et_userName.getText().toString().trim();
        String userDetails_brandModel = et_brandModel.getText().toString().trim();
        String userDetails_plateNum = et_plateNum.getText().toString().trim();
        String userDetails_problem = spin_problems.getSelectedItem().toString().trim();

        if(TextUtils.isEmpty(userDetails_name) || TextUtils.isEmpty(userDetails_brandModel) || TextUtils.isEmpty(userDetails_plateNum)){
            Toast.makeText(getActivity(),"Please fill in all the fields", Toast.LENGTH_SHORT).show();
        } else {
            UserReport user_report = new UserReport(userDetails_ID, userDetails_vehicleType, userDetails_name, userDetails_brandModel, userDetails_plateNum, userDetails_problem, getLong, getLat);
            databaseReference.push().setValue(user_report);
            Toast.makeText(getActivity(), "Saved Successfully", Toast.LENGTH_SHORT).show();

            //getActivity().getActionBar().setTitle("Mech Home");
            //getFragmentManager().beginTransaction().replace(R.id.mechcontainer,new MechHomeFragment()).commit();
            getActivity().finish();
        }

    }

//**MY BUTTON:**

 btn_userdetails.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View view) {
                LocationManager locationManager = (LocationManager) getActivity().getSystemService(Context.LOCATION_SERVICE);
                LocationListener locationListener = new UserDetailsFragment.MyLocationListener();
                if ((ActivityCompat.checkSelfPermission(getContext(), android.Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED || ActivityCompat.checkSelfPermission(getContext(), android.Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED)) {
                    locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 1000, 1, locationListener);
                    Toast.makeText(getContext(), "OK", Toast.LENGTH_SHORT).show();   // Toast is showing

                    userDetails();

                }
            }
        });`

**Comment by komangsidhiartha** [comment]
I’m sorry if I read it wrong, but how is this aquery problem? I didn’t see any aquery call on the sample code

if this is general android problem, you can post a question on stackoverflow
