### ISSUE TITLE
shouldDelay method for file

### ISSUE THREAD

**Issue by florianmski** [tinyeeliu/androidquery#15]
Hi,
This is not an issue but a feature request.
Is it possible to write a `shouldDelay` method that take a file or a path instead of an url in order to load asynchronously an image that has not be cached by AQUery before ?
For exemple, I'm writing an app where I download myself a .zip containing images. Then I save them in a folder in the sdcard and I want to display them in a list/gridview with the benefits of the `shouldDelay` method.
Thanks again for this awesome lib, I use it a lot in Traktoid : https://github.com/florianmski/Traktoid

**Comment by tinyeeliu** [comment]
I opened a ticket to track here:
http://code.google.com/p/android-query/issues/detail?id=50

**Comment by florianmski** [comment]
Thanks!
