### ISSUE TITLE
Support for Http GET, POST, PUT, DELETE

### ISSUE THREAD

**Issue by ghost** [tinyeeliu/androidquery#17]
As far as the docs are concerned, GET & POST are supported, is there support for PUT & DELETE?

**Comment by jonasbark** [comment]
No it isn't, yet. I hacked it in myself.

**Comment by tinyeeliu** [comment]
there isnt support for put and delete.

sent from mobile
On May 23, 2012 4:53 PM, "Raymond Wanyoike" <
reply@reply.github.com>
wrote:

**Comment by bilalsammour** [comment]
@jonasbark , great job, how did you hack? Could you share the modified library?
