### ISSUE TITLE
Potential null pointer access in AbstractAjaxCallback

### ISSUE THREAD

**Issue by DavidWiesner** [tinyeeliu/androidquery#22]
Hi Peter,

there are missing brackets in the If-condition in the private Method httpDo. So you will get an NullPointerException iff header is null.

```
private void httpDo(...)
```

...

```
-       if(GZIP && headers == null || !headers.containsKey("Accept-Encoding")){
+       if(GZIP && (headers == null || !headers.containsKey("Accept-Encoding"))){
```

regards, 
David

**Comment by tinyeeliu** [comment]
Fixed for future release. Thanks for reporting. :)
