### ISSUE TITLE
[new feature request] network traffic

### ISSUE THREAD

**Issue by soarcn** [tinyeeliu/androidquery#27]
it's would be a widely used functionality be used, esp. in China. picture (or any large size file) download only allowed in wifi(or 3G ) enviorment, and of course, this is a option user can choose. this would be a functions without any dependency. good to have.

**Comment by tinyeeliu** [comment]
So this is a feature to check if a wifi or metered network is in use.

**Comment by soarcn** [comment]
yes, but also need to check if picture has been cached(downloaded) already, I guess some change would be needed in BitmapAjaxCallback
