### ISSUE TITLE
Update dialog korean translation

### ISSUE THREAD

**Issue by skyisle** [tinyeeliu/androidquery#28]
https://androidquery.appspot.com/api/market response has wrong korean translation.
"title" : "Update Notice" need to be "title" : "새로운 기능"

btw, any plan to open source appspop's code?

**Comment by tinyeeliu** [comment]
Updated at server.

Currently have no plan to open source as it's not using a method that's offically supported by Google.

**Comment by skyisle** [comment]
Thanks for quick response. 

I found another translation improvement.

"rate": "검토" => "rate": "리뷰"
