### ISSUE TITLE
Where download 0.25.7 BETA?

### ISSUE THREAD

**Issue by youxiachai** [tinyeeliu/androidquery#44]
Release Notes  have 0.25.7 BETA info,but I can't find code google dowloads .

**Comment by tinyeeliu** [comment]
Haven't uploaded it yet. It's a small change from 0.25.6 so that should
still works for you.

**Comment by brk3** [comment]
@androidquery Would you mind sending a quick note to the mailing list each time you cut a release?  Apart from being useful to know in general, it helps me know I need to update the artifacts in Maven central.

**Comment by tinyeeliu** [comment]
Yes.

I usually don't tweet about beta release.

But for regular release I usually post on Tweeter and Facebook.
