### ISSUE TITLE
[BUG] Cache incomplete content when network error during httpDo

### ISSUE THREAD

**Issue by gebing** [tinyeeliu/androidquery#45]
1. Make a ajax call which generating file cache, eg. aq.ajax(url, File.class, cb);
2. If there is network error during AbstractAjaxCallback#copy(InputStream is, OutputStream os, String encoding, int max), there will generate a cached file with incomplete content.
3. Make another ajax call with same url and cache, eg. aq.ajax(url, File.class, expire, cb), AQuery will return success with incomplete content file.

Suggestion:

in function AbstractAjaxCallback#copy, there shuold catch exception and remove incomplete cache file

**Comment by tinyeeliu** [comment]
Fixed in "dev" branch. Will be included next release.

**Comment by gebing** [comment]
I have a Pull Reqeust #53 for this Issue and other two other bug fix, pls consider it.
