### ISSUE TITLE
[BUG] ah in AbstractAjaxCallback is overwrite and cleared by ah in AbstractAQuery

### ISSUE THREAD

**Issue by gebing** [tinyeeliu/androidquery#46]
What steps will reproduce the problem?
1. Just run AjaxAuthActivity in demo project
2. Debug output ah in networkWork() of AbstractAjaxCallback.java
3. You will see ah is null and is not set by cb.auth(this, AQuery.AUTH_PICASA, AQuery.ACTIVE_ACCOUNT);

What is the expected output? What do you see instead?
Expect ah is not null, but ah is null

What version of the product are you using? On what operating system
Release 0.25.8

Please provide any additional information below.
AbstractAjaxCallback 's ah is set to AbstractAQuery's ah in AbstractAQuery's invoke() function.

**Comment by gebing** [comment]
It will also overwrite AbstractAjaxCallback's progress/transformer. 
Maybe you should modified AbstractAQuery#invoke(AbstractAjaxCallback<?, K> cb), 
From:
        cb.auth(ah);
        cb.progress(progress);
        cb.transformer(trans);
To:

```
    if (ah != null) cb.auth(ah);
    if (progress != null) cb.progress(progress);
    if (trans != null) cb.transformer(trans);
```

But i don't think it is a good solotion, because i think even if AbstractAQuery has its own ah/progress/trans, it should not overwtite AbstractAjaxCallback's ah/progress/transformer settings

**Comment by tinyeeliu** [comment]
Fixed. The fix is identical to yours.

The params stored in AQuery is cleared for each ajax request and it needs to be reset every ajax request. So the fix is ok and by design.

Thanks for reporting. :)
