### ISSUE TITLE
no result when the server status code is not 200

### ISSUE THREAD

**Issue by ghatasheh** [tinyeeliu/androidquery#68]
Hello

When the server send status code other than 200, the body always null!

for example: 

```
<?php 

    header("HTTP/1.1 433 OK");

    $response = array();
    $response['key'] = 'value';
    echo json_encode($response);
?>
```

In AQuery, this will show status code 433 but the body is null!

Could you please help in this?

Thank you.

**Comment by tinyeeliu** [comment]
Try AjaxStatus.getError()

http://android-query.googlecode.com/svn/trunk/javadoc/com/androidquery/callback/AjaxStatus.html#getError()

When response is 433, chances are the body is not the type that you
expected. For example, an image will return as an error html page.
So when response code is an error, result is always null. getError() should
give you a string of the page returned.

On Tue, Nov 26, 2013 at 11:13 PM, Hisham Ghatasheh <notifications@github.com

**Comment by ghatasheh** [comment]
Thank you sir!
