### ISSUE TITLE
Suggerstion

### ISSUE THREAD

**Issue by iNoles** [tinyeeliu/androidquery#7]
I would like to add a boolean method like isVisible() like 
[code]return view != null && view.getVisibility() == View.VISIBILE[/code]

This would be extremely useful for developers like in Android when they have to check portrait and landscape specific view.

**Comment by tinyeeliu** [comment]
Thanks for the suggestion. Going to add this check for the visible, invis, and gone methods.

**Comment by tinyeeliu** [comment]
Updated in dev branch. Will be pushed to master next release.
