### ISSUE TITLE
Source code version

### ISSUE THREAD

**Issue by charafau** [tinyeeliu/androidquery#80]
On google code site, in download section the newest version is 0.26.8, but in source code there's still 0.25.9. 

Don't know what kind of version is in sonatype repository and / or maven central but version should be fixed.

Thanks

**Comment by charafau** [comment]
I checked code in repository. It's not the newest one.

**Comment by vkotovv** [comment]
I think [dev](https://github.com/androidquery/androidquery/tree/dev) branch is used for ongoing development. Anyway, it is updated now, the issue can be closed.

**Comment by tinyeeliu** [comment]
google code doesnt allow making new download anymore. maybe should remove
all the download in google code to avoid confusion.

sent from mobile
