### ISSUE TITLE
Using a different Bitmap Config?

### ISSUE THREAD

**Issue by Gryzor** [tinyeeliu/androidquery#84]
Is there any way to use ARG_4444 or any other non 8888 option? I haven't seen a way to do it.

Thanks.

**Comment by tinyeeliu** [comment]
Theres no method to set this. But it should be a one line change in
BitmapAjaxcallback.java

sent from mobile

**Comment by stepango** [comment]
ARG_4444 is deprecated now since 4.4

**Comment by Gryzor** [comment]
> ARG_4444 is deprecated now since 4.4

I know, it was just an example. 4444 is deprecated, but other formats are not. 

@androidquery thanks.
