### ISSUE TITLE
Loading images in a ListView

### ISSUE THREAD

**Issue by sergicastellsague** [tinyeeliu/androidquery#89]
I'm having an issue:

When I scroll fast a listView with images, as recycle occurs, images are displayed on the wrong item.

Any tips about how to fix this?

**Comment by Brblol** [comment]
Have you tried using a plane old holder pattern adapter?

**Comment by sergicastellsague** [comment]
What do you mean with "old holder pattern adapter"?

**Comment by sergicastellsague** [comment]
Okay. What I did is creating a helper which does the following:

ListView sends its row imageview (with a unique TAG set), to this helper, aswell as the URL of the image to fetch from internet.

THe helper fetches the image, and once received, I check if the imageview has the same TAG still, and if so, I display the image. Otherwise, do nothing.
