### ISSUE TITLE
Multipart request doesn't contain headers passed by parameter

### ISSUE THREAD

**Issue by polysiya** [tinyeeliu/androidquery#9]
HttpURLConnection requires only two properties.

conn.setRequestProperty("Connection", "Keep-Alive");
conn.setRequestProperty("Content-Type", "multipart/form-data;charset=utf-8;boundary="+ boundary);

Headers passed by parameter should be contained.

**Comment by tinyeeliu** [comment]
It's fixed in 0.20.1

http://code.google.com/p/android-query/downloads/list

or here:
https://github.com/androidquery/androidquery/blob/dev/src/com/androidquery/callback/AbstractAjaxCallback.java

**Comment by polysiya** [comment]
Oh.. I didn't check recent beta version..
Thank you for fast update :D
